/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import java.awt.Font;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.*;


/**
 *
 * @author nestor2502
 */
public class Registro extends javax.swing.JFrame {
     Base base;
     int cont =0;
     Historial his;
     String llave;
     Activacion m;
     boolean activacion= false;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setVisible(false);
        this.setTitle("Proyecto 3");
        this.setResizable(false);
        regresar.setContentAreaFilled(false);
        crear.setContentAreaFilled(false);
        
         TextPrompt placeholder = new TextPrompt("Nombre completo", nombre);
         placeholder.changeAlpha(0.75f);
         placeholder.changeStyle(Font.ITALIC);
         
         TextPrompt placeholder1 = new TextPrompt("Nombre de usuario", usuario);
         placeholder1.changeAlpha(0.75f);
         placeholder1.changeStyle(Font.ITALIC);
         
         TextPrompt placeholder2 = new TextPrompt("Direccion de correo electronico", correo);
         placeholder2.changeAlpha(0.75f);
         placeholder2.changeStyle(Font.ITALIC);
         
         TextPrompt placeholder3 = new TextPrompt("Contraseña", contrasena);
         placeholder3.changeAlpha(0.75f);
         placeholder3.changeStyle(Font.ITALIC);
         

         try{
             ObjectInputStream recuperando_fichero= new ObjectInputStream(new FileInputStream("Test2"));
             base =(Base )recuperando_fichero.readObject();
             recuperando_fichero.close();}
          catch(IOException e){
                	System.out.println(e.getMessage());
                }
                catch(ClassNotFoundException e){
                    System.out.println(e.getMessage());
                	
             } 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        contrasena = new javax.swing.JPasswordField();
        regresar = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Comienza tu aventura con una cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 520, 60));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 560, 50));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 560, 50));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 560, 50));

        crear.setBackground(new java.awt.Color(90, 90, 78));
        crear.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        crear.setForeground(new java.awt.Color(240, 240, 240));
        crear.setText("Crear cuenta");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 190, 60));
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 560, 50));

        regresar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        regresar.setForeground(new java.awt.Color(254, 254, 254));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        fondo2.setBackground(new java.awt.Color(38, 38, 38));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3/1080x720-00001.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
          int contador=0;
          int correcto1 = 0;
          int correcto2 =0;
          int correcto=0;
          String nombre1 = nombre.getText().trim();
          String usuario1 = usuario.getText().trim();
          String correo1 =correo.getText().trim();
          String contraseña1 =contrasena.getText().trim();
          //System.out.println("La contraseña es"+contraseña1);
          llave = "";
          Usuario usuario; 
          Historial his;
       
        
        //verificacion de email
        String email = correo1;
        if(email.equals("")==false||!email.equals(" ")==false){
         for(int i = 0 ; i<email.length(); i++){

             	  if(email.charAt(i)=='@')

             	  	  correcto1 ++;
                  if(email.charAt(i)=='.')

             	  	  correcto2 ++;
             }

             if(correcto1 == 0 && correcto2==0){

             	 //System.out.println("Incorrecto");
             	 JOptionPane.showMessageDialog(null, "Correo incorrecto");
             }
             else{
         //verifica que los campos no esténvacios     
            if(nombre1.equals("")||usuario1.equals("")||correo1.equals("")||contraseña1.equals("")){
               JOptionPane.showMessageDialog(null, "No dejes campos vacios");
        }
        else contador++;}
        //se intenta crear el usuario si es que existe
        if(correcto1 >0  && correcto2 > 0){
                // System.out.println("se realizo");
                llave = email.concat(contraseña1);
                usuario = new Usuario(nombre1, usuario1, email,contraseña1);
                //se verifica si existe el nombre de usuario
                if(base.existeNombreUsuario(usuario)){
                    JOptionPane.showMessageDialog(null, "Nombre de usuario ya registrado");
                   // System.out.println("filtro 1.1: ay existe el nombre de usuario");
                }
                else{
                     correcto++;
                     //System.out.println("filtro 1.1: superado");
                    }
                if(base.existeCorreo(usuario)){
                     JOptionPane.showMessageDialog(null, "Correo ya registrado");  
                     //System.out.println("filtro 1.2: ay existe el correo");
                }  
                else{
                   correcto++;
                    //System.out.println("filtro 1.2: superado");
                }
                if(correcto>=2){
                 //System.out.println("filtro final: se creará el usuario");
                 base.agrega(usuario);
                // System.out.println("filtro final: se creó el usuario");
                  //System.out.println("La llave es: "+llave);
                  try{
                ObjectOutputStream escribiendo_fichero = new ObjectOutputStream(new FileOutputStream("Test2"));
                escribiendo_fichero.writeObject(base);
                escribiendo_fichero.close();
                }
                 catch(IOException e){
                	System.out.println(e.getMessage());
                }
                 //his = new Historial(base,llave);
                 cont++;
                 activacion = true;
                 this.dispose();
                }
             }}
        else{
            if(nombre1.equals("")||usuario1.equals("")||correo1.equals("")||contraseña1.equals(""))
               JOptionPane.showMessageDialog(null, "No dejes campos vacios");
         }
         
        
         
        
        
        
        
            
    }//GEN-LAST:event_crearActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
         if(cont>0){
        Historial his= new Historial(base,llave);}
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        /**    
        if(cont>0){
        Historial his= new Historial(base,llave);}
            else if(cont==0){
        m = new Activacion(false);
       try{//escribiendo archivo
                ObjectOutputStream escribiendo_fichero = new ObjectOutputStream(new FileOutputStream("Inicio"));
                escribiendo_fichero.writeObject(m);
                escribiendo_fichero.close();
               
                }
                catch(Exception e){
                System.out.println("hay un error");
                }}*/
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crear;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
