/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import java.util.*;
import java.io.*;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author nestor2502
 */
public class Ventana1 extends javax.swing.JFrame {
    public Base base;
    int i=0;
    Activacion personal_recuperado;
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(true);
        this.setTitle("Proyecto 3");
        this.setResizable(false);
         iniciar.setContentAreaFilled(false);
         registrarse.setContentAreaFilled(false);
         salir.setContentAreaFilled(false);
         //se esta comentadndo para poder leer la base y no crear una nueva
         //base = new Base();
         try{   
             
                //ObjectOutputStream escribiendo_fichero = new ObjectOutputStream(new FileOutputStream("/home/nestor2502/Escritorio/Test1.txt"));
                
                 /**
                 ObjectOutputStream escribiendo_fichero = new ObjectOutputStream(new FileOutputStream("Test2"));    
                 escribiendo_fichero.writeObject(base);
                 escribiendo_fichero.close();
                 */
                 ObjectInputStream recuperando_fichero= new ObjectInputStream(new FileInputStream("Test2"));
                 base =(Base )recuperando_fichero.readObject();
                recuperando_fichero.close();

                }
                 catch(IOException e){
                	System.out.println("1   "+e.getMessage());
                }
                catch(ClassNotFoundException e){
                    System.out.println("2   "+e.getMessage());
                	
                    }
        
}
    
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("proyecto3/586273b931349e0568ad89df.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarse = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarse.setBackground(new java.awt.Color(90, 90, 78));
        registrarse.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        registrarse.setForeground(new java.awt.Color(241, 241, 240));
        registrarse.setText("Registrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 220, 100));

        iniciar.setBackground(new java.awt.Color(90, 90, 78));
        iniciar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        iniciar.setForeground(new java.awt.Color(240, 240, 240));
        iniciar.setText("Iniciar sesion");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 210, 100));

        salir.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(254, 254, 254));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3/PicsArt_05-26-12.03.49.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        Registro registro = new Registro();
        registro.setVisible(true);
    }//GEN-LAST:event_registrarseActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        IniciarSesion inicia = new IniciarSesion();
        //this.setVisible(false);
        //this.setVisible(false);
        inicia.setVisible(true);
        
        
        //this.setVisible(false);
        
         
        
    }//GEN-LAST:event_iniciarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
         
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       //this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
